# Generated by Django 4.2 on 2023-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_reference_links_sustainable_products_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainable_products',
            name='product_image',
            field=models.FileField(default='', upload_to='user/uploads/'),
        ),
    ]
