# Generated by Django 4.2 on 2023-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sustainable_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainable_products',
            name='product_image',
            field=models.FileField(default=None, null=True, upload_to='user/uploads/'),
        ),
    ]
